done again

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,26 +1,26 @@
 #!/usr/bin/env bash
-# secure transfering of file to server
-
-#checking whether the four requirement is fullfilled
-
+# Checking for command-line argument
 if [ $# -lt 4 ]
-then 	
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit 1
+then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-#securely sending file to server by disabling StrictHostKeyChecking
+# Assigning Arguments to variables
 
 path_to_file=$1
 ip=$2
 username=$3
-path_to_key=$4
+path_to_ssh_key=$4
 
-scp -o "StrictHostKeyChecking no" -i "$path_to_file" "$path_to_key" "$username@$ip:~/"
 
+# Disabbling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# Checking if the transfer was successful
 if [ $? -eq 0 ]
 then
-	echo "transferred"
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-	echo "Not transferred"
+  echo "FILE TRANSFER FAILED"
 fi
